#!/usr/bin/perl

use Encode;
# use utf8;

# binmode STDOUT, ":utf8";

open FILE, shift or die "Unesite ime datoteke.\n";

%chars = (

	'Ā' => 'A',
	'Ē' => 'E',
	'Ī' => 'I',
	'Ō' => 'O',
	'Ū' => 'U',

	'Ă' => 'A',
	'Ĕ' => 'E',
	'Ĭ' => 'I',
	'Ŏ' => 'O',
	'Ŭ' => 'U',

	'ă' => 'a',
	'ĕ' => 'e',
	'ĭ' => 'i',
	'ŏ' => 'o',
	'ŭ' => 'u',
	
	'ā' => 'a',
	'ē' => 'e',
	'ī' => 'i',
	'ō' => 'o',
	'ū' => 'u',
	'ȳ' => 'y',
	
	'ä' => 'a',	
	'ë' => 'e',
	'ï' => 'i',
	'ö' => 'o',
	'ü' => 'u',

	'á' => 'a',
	'é' => 'e',
	'í' => 'i',
	'ó' => 'o',
	'ú' => 'u',
	
	'à' => 'a',
	'è' => 'e',
	'ì' => 'i',
	'ò' => 'o',
	'ù' => 'u',
	
	'â' => 'a',
	'ê' => 'ae',
	'î' => 'i',
	'ô' => 'o',
	'û' => 'u',

	'Ê' => 'Ae'
);

while(<FILE>){
	
	chomp;
	
# 	$_ = decode("iso-8859-1", $_);

	for $char (keys %chars){
		
		s/$char/$chars{$char}/g;
		s/[-_\^\/]//g;
		s/\s+/ /g;
	}
	print "$_\n";
}






